### ISSUE TITLE
How to track websocket connections?

### ISSUE THREAD

**Issue by BFamzz** [BFamzz/uWebSockets#1]
Hi @pavulon I noticed in the manual strongly disapproves of using std::map to track websocket connections.

Can you please explain how websocket connections can be tracked with the userData structure.

For instance assuming we have 3 websocket connections (user1, user2 and user3) with unique ids (assigned via userData struct), how can we access the websocket connection outside of the websocket handler (i.e how can a message be sent to user1 socket in a "get" handler).

This [issue](https://github.com/uNetworking/uWebSockets/issues/896) mentions the use of placement new. 

Can you please show how to do that with a minimal example?

Thanks.

**Comment by pavulon** [comment]
Not sure why you're asking me but okay.

I think the docs mean that you shouldn't use std::map to associate custom data with ws objects (like user id), because you can already do it with userData and it's just more efficient — no need to do a map lookup in every ws handler.

For your use case, map is fine.

**Comment by BFamzz** [comment]
> Not sure why you're asking me but okay.

Thanks for your response. I tried getting the clarification in the main project repo but the author wasn't forthcoming.

> For your use case, map is fine

Alright. Thanks so much.
